openapi: 3.0.2
info:
  version: 1.0.0
  title: IssueTracker
  description: "This is the Open API documentation for the REST API of our beloved application **IssueTracker** deployed at <https://issuetrackerv1.herokuapp.com/>. <br>All operations are executable. Operations that make changes to the domain require authentication. In this case, you must **Authorize** your request by providing the token value you got when you created the tweet."
servers:
  - url: 'https://issuetrackerv1.herokuapp.com/'
paths:
  /:
    get:
      tags:
        - Issues
      summary: Retrieves all the Issues
      operationId: all_issues_as_json
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'

components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        subject:
          type: string
          example: 'Subject'
        description:
          type: string
          example: 'Description'
        assign:
          type: string
          example: 'Assign'
        created_at:
          type: string
          format: date-time
          example: 'Wed, 12 Apr 2023 13:52:06.671832000 UTC +00:00'
        updated_at:
          type: string
          format: date-time
          example: 'Wed, 12 Apr 2023 13:52:06.671832000 UTC +00:00'
        severity:
          type: string
          example: 'Wishlist'
        priority:
          type: string
          example: 'High'
        issue_types:
          type: string
          example: ''
        issue_type:
          type: string
          example: 'Bug'
        blocked:
          type: boolean
          example: true
        deadline:
          type: string
          format: date-time
          example: '05/05/2023'
        watcher:
          type: string
          example: 'Gabriel del Valle'
        watcher_ids:
          type: array
          items:
            type: integer
        status:
          type: string
          example: 'New'
        created_by:
          type: string
          example: 'Gabriel del Valle'